from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from time import sleep

opts=webdriver.ChromeOptions()
opts.add_experimental_option("detach",True)
driver=webdriver.Chrome(options=opts)
driver.get("https://demoqa.com/automation-practice-form")
driver.maximize_window()
sleep(2)
f_name=driver.find_element(By.ID,"firstName")
f_name.send_keys("Selena")
l_name=driver.find_element(By.ID,"lastName")
l_name.send_keys("Ray")
email=driver.find_element(By.ID,"userEmail")
email.send_keys("sele123@gmail.com")
gender=driver.find_element(By.XPATH,"//label[text()='Female']")
gender.click()
no=driver.find_element(By.ID,"userNumber")
no.send_keys("9838723210")
subject=driver.find_element(By.ID,"subjectsInput")
subject.send_keys("Arts")
sleep(2)
subject.send_keys(Keys.ENTER)
h1=driver.find_element(By.XPATH,"//label[text()='Reading']")
h1.click()
h2=driver.find_element(By.XPATH,"//label[text()='Music']")
h2.click()
pic=driver.find_element(By.ID,"uploadPicture")
pic.send_keys(r"D:\Screenshot (12).png")
address=driver.find_element(By.ID,"currentAddress")
address.send_keys("Pratap Nagar,Jaipur")
s=driver.find_element(By.ID,"state")
s.click()
sleep(1)
state=driver.find_element(By.XPATH,"//div[text()='Rajasthan']")
state.click()
c=driver.find_element(By.ID,"city")
c.click()
sleep(1)
city=driver.find_element(By.XPATH,"//div[text()='Jaipur']")
city.click()
submit=driver.find_element(By.ID,"submit")
submit.click()
sleep(2)
driver.quit()