from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
opts=webdriver.ChromeOptions()
opts.add_experimental_option("detach",True)
driver=webdriver.Chrome(options=opts)
driver.get("https://the-internet.herokuapp.com/")
driver.maximize_window()
checkbox_link =driver.find_element(By.LINK_TEXT, "Checkboxes")
drag_drop_link =driver.find_element(By.PARTIAL_LINK_TEXT, "Drag")
print("Both links found!")
li_elements =driver.find_elements(By.TAG_NAME, "li")
print("Total no. of elements:", len(li_elements))
driver.get("https://the-internet.herokuapp.com/tables")
sleep(2)
site =driver.find_element(By.XPATH,"//table[@id='table1']//td[text()='jdoe@hotmail.com']/following-sibling::td[1]")
print(site.text)
delete_link =driver.find_element(By.XPATH,"//table[@id='table1']//td[text()='Bach']/following-sibling::td//a[text()='delete']")
print("Delete link found")
second_table = driver.find_element(By.XPATH,"(//table)[2]")
print("Second table found")
cell = driver.find_element(By.XPATH,"//table[@id='table2']//td[text()='$100.00']")
parent_row = cell.find_element(By.XPATH,"./parent::tr")
print(parent_row.text)
driver.quit()